version: '3.5'
services:
  lungmask:
    build: lungmask
    container_name: lungmask_for_streamlit
    hostname: lungmask_for_streamlit
    environment:
      - LUNGMASK_HOSTNAME=lungmask_for_streamlit
      - LUNGMASK_PORT=8000
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONBUFFERED=1
    command: python3 /src/listen.py
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./lungmask:/src/

  streamlit:
    build:
      context: streamlit-container
      dockerfile: Dockerfile.testing
    container_name: streamlit
    hostname: streamlit
    environment:
      - LUNGMASK_HOSTNAME=lungmask_for_streamlit
      - LUNGMASK_PORT=8000
      - CT_MUSCLE_SEG_HOSTNAME=ct_muscle_seg
      - CT_MUSCLE_SEG_PORT=8000
      - CT_FAT_MEASURE_HOSTNAME=ct_visceral_fat
      - CT_FAT_MEASURE_PORT=8000
      - LUNGMASK_CONVERTER_HOSTNAME=lungmask_converter
      - LUNGMASK_CONVERTER_PORT=8000
      - COVID_DETECTOR_HOSTNAME=covid_detector
      - COVID_DETECTOR_PORT=8000
      - COVID_DETECTOR_SEG_HOSTNAME=covid_detector_seg
      - COVID_DETECTOR_SEG_PORT=8000
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=dockercompose
      - PYTHONPATH=/src/
      - DEBUG=1
      - TESTING_DIR=/app/source/testing/nifti
      - TESTING_OUT_DIR=/app/output/
      - TESTING_INPUT_NAME=image.nii.gz
    ports:
      - "8503:8501"
    command: python3 /src/testing/test_lungmask.py
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./streamlit-container:/src/
      - ./output:/app/output

volumes:
  app-volume:

