version: '3'
services:
  lungmask:
    build: lungmask
    container_name: lungmask
    hostname: lungmask
    ports:
      - "8501:8501"
    command: streamlit run main.py


#  streamlit:
#    build: streamlit
#    container_name: streamlit
#    hostname: streamlit
#    ports:
#      - "3000:3000"
#    command: tail -F anything

