version: '3.5'
services:
  lungmask:
    build: lungmask
    container_name: lungmask_for_streamlit
    hostname: lungmask_for_streamlit
    environment:
      - LUNGMASK_HOSTNAME=lungmask_for_streamlit
      - LUNGMASK_PORT=8000
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONBUFFERED=1
    command: python3 /src/listen.py
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./lungmask:/src/


  ct_muscle_seg:
    build:
      context: CTMuscleSegmentation
      shm_size: '2gb'
    shm_size: '2gb'
    container_name: ct_muscle_seg
    hostname: ct_muscle_seg
    command: python3 /src/listen.py
    environment:
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONUNBUFFERED=1
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./CTMuscleSegmentation:/src

  ct_visceral_fat:
    build: CTVisceralFat
    container_name: ct_visceral_fat
    hostname: ct_visceral_fat
    command: python3 /src/listen.py
    environment:
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONUNBUFFERED=1
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./CTVisceralFat:/src

  lungmask_converter:
    build: lungmask-1
    container_name: lungmask_converter
    hostname: lungmask_converter
    command: python3 /src/listen.py
    environment:
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONUNBUFFERED=1
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./lungmask-1:/src

  streamlit:
    build: streamlit-container
    container_name: streamlit
    hostname: streamlit
    environment:
      - LUNGMASK_HOSTNAME=lungmask_for_streamlit
      - LUNGMASK_PORT=8000
      - CT_MUSCLE_SEG_HOSTNAME=ct_muscle_seg
      - CT_MUSCLE_SEG_PORT=8000
      - CT_FAT_MEASURE_HOSTNAME=ct_visceral_fat
      - CT_FAT_MEASURE_PORT=8000
      - LUNGMASK_CONVERTER_HOSTNAME=lungmask_converter
      - LUNGMASK_CONVERTER_PORT=8000
      - COVID_DETECTOR_HOSTNAME=covid_detector
      - COVID_DETECTOR_PORT=8000
      - COVID_DETECTOR_SEG_HOSTNAME=covid_detector_seg
      - COVID_DETECTOR_SEG_PORT=8000
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=dockercompose
      - PYTHONPATH=/src/
      - DEBUG=1
    ports:
      - "8503:8501"
    command: streamlit run /src/main.py
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./streamlit-container:/src/

  covid_detector:
    build: covid_lesion_detection
    container_name: covid_detector
    hostname: covid_detector
    command: python3 /src/listen.py
    environment:
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONBUFFERED=1
      - PYTHONPATH=/src
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./covid_lesion_detection:/src/

  covid_detector_seg:
    build: covid_lesion_detection_seg
    container_name: covid_detector_seg
    hostname: covid_detector_seg
    command: python3 /src/listen.py
    environment:
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONBUFFERED=1
      - PYTHONPATH=/src
    volumes:
      - app-volume:/app/data_share
      - ./source:/app/source
      - ./covid_lesion_detection_seg:/src/

volumes:
  app-volume:

