version: '3'
services:
  lungmask:
    build: lungmask
    container_name: lungmask_for_streamlit
    hostname: lungmask_for_streamlit
    command: tail -F anything

  streamlit:
    build: streamlit-container
    container_name: streamlit
    hostname: streamlit
    ports:
      - "8502:8501"
    command: streamlit run main.py

