version: '3.5'
services:
  lungmask:
    build: lungmask
    container_name: lungmask_for_streamlit
    hostname: lungmask_for_streamlit
    environment:
      - LUNGMASK_HOSTNAME=lungmask_for_streamlit
      - LUNGMASK_PORT=8000
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONBUFFERED=1
      - ENVIRONMENT=dockercompose
    command: python3 start.py
    volumes:
      - app-volume:/app/data_share

  ct_muscle_seg:
    build:
      context: CTMuscleSegmentation
      shm_size: '2gb'
    shm_size: '2gb'
    container_name: ct_muscle_seg
    hostname: ct_muscle_seg
    command: tail -F anything


  streamlit:
    build: streamlit-container
    container_name: streamlit
    hostname: streamlit
    environment:
      - LUNGMASK_HOSTNAME=lungmask_for_streamlit
      - LUNGMASK_PORT=8000
      - DATA_SHARE_PATH=/app/data_share
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=dockercompose
    ports:
      - "8502:8501"
    command: streamlit run main.py
    volumes:
      - app-volume:/app/data_share


volumes:
  app-volume:

